cart/urls.py
from django.urls import path
from . import views

app_name = "cart"

urlpatterns = [
    path("", views.cart_detail, name="cart_detail"),
    path("add/<str:room_number>/", views.cart_add, name="cart_add"),
    path("remove/<str:room_number>/", views.cart_remove, name="cart_remove"),
]

hotel/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include
from django.contrib.staticfiles.urls import staticfiles_urlpatterns

urlpatterns = [
    path("", include("service.urls", namespace="service")),
    path("cart/", include("cart.urls", namespace="cart")),
    path("registration", include("service.registration_urls")),
    path("admin/", admin.site.urls),
]


# Serve static files during development
# urlpatterns += staticfiles_urlpatterns()
# urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)


if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

service/urls.py
from django.urls import path, include
from . import views
from django.contrib.auth import views as auth_views
from django.contrib.auth.decorators import login_required


app_name = "service"

urlpatterns = [
    path("", views.Home.as_view(), name="home"),
    path("restaurant/", views.Restaurant_page.as_view(), name="restaurant"),
    path("restaurant/<str:name>/", views.dish_r, name="dish_r"),
    path("wellness/<str:name>/", views.dish_w, name="dish_w"),
    path("about/", views.about, name="about"),
    path("account/", views.account, name="account"),
    path("gallery/", views.gallery, name="gallery"),
    path("wellness/", views.wellness, name="wellness"),
    path("register/", views.register, name="register"),
    path("edit/", views.edit, name="edit"),
    path("events/", views.event, name="event"),
    path("event_info/<str:name>/", views.event_info, name="event_info"),
    path("event_info/delete/<int:id>/", views.delete_reminder, name="delete_r"),
    path("roomt/<int:id>/", views.rooms, name="rooms"),
    path("roomtypes/", views.Roomtype, name="roomtype"),
    path("meeting/", views.meeting, name="meeting"),
    path("booking/", views.booking, name="booking"),
    path("admin_page/", views.admin_page, name="admin"),
    path("email/", views.email_view, name="email_view"),
    path("success/", views.success_page, name="success_page"),
    path('contact/', views.text, name='contact_view'),
    path('success/', views.success_page, name='success_page'),
]

cart/models.py
from django.db import models

# Create your models here.

cart/forms.py
from django import forms

ROOM_DURATION_CHOICES = [(i, str(i)) for i in range(1, 31)]
NUMBER_OF_GUEST_CHOICES = [(i, str(i)) for i in range(1, 7)]


class CartAddRoomForm(forms.Form):
    duration = forms.TypedChoiceField(
        choices=ROOM_DURATION_CHOICES, coerce=int, initial=1
    )
    number_of_guest = forms.TypedChoiceField(
        choices=NUMBER_OF_GUEST_CHOICES, coerce=int, initial=1
    )
    override_duration = forms.BooleanField(
        required=False, initial=False, widget=forms.HiddenInput
    )
    override_number_of_guest = forms.BooleanField(
        required=False, initial=False, widget=forms.HiddenInput
    )

cart/views.py
from django.shortcuts import render

from django.shortcuts import render, redirect, get_object_or_404
from django.views.decorators.http import require_POST
from service.models import Room
from .cart import Cart
from .forms import CartAddRoomForm



# payments/views.py




@require_POST
def cart_add(request, room_number):
    cart = Cart(request)
    room = get_object_or_404(Room, number=room_number)
    form = CartAddRoomForm(request.POST)
    if form.is_valid():
        cd = form.cleaned_data
        cart.add(
            room_instance=room,
            duration=cd["duration"],
            number_of_guest=cd["number_of_guest"],
            override_duration=cd["override_duration"],
            override_number_of_guest=cd["override_number_of_guest"],
            start_date=request.POST.get("start_date"),
            end_date=request.POST.get("end_date"),
        )

    return redirect("cart:cart_detail")


@require_POST
def cart_remove(request, room_number):
    cart = Cart(request)
    room_num = get_object_or_404(Room, number=room_number)
    cart.remove(room_num.number)
    return redirect("cart:cart_detail")


def cart_detail(request):
    cart = Cart(request)
    for item in cart:
        item["update_room_form"] = CartAddRoomForm(
            initial={
                "duration": item["duration"],
                "number_of_guest": item["number_of_guest"],
                "override_duration": True,
                "override_number_of_guest": True,
                "start_date": item.get("start_date"),
                "end_date": item.get("end_date"),
            }
        )

    return render(request, "cart/detail.html", {"cart": cart})

cart/templates/cart/detail.html
{% extends "service/base.html" %}
{% load static %}
{% block title %}
 reserved rooms
{% endblock %}
{% block content %}
 <h1 class="rssv">RESERVED ROOMS FOR BOOKING</h1>
 
 <div class="tcarry">
 <table class="cart">
   <thead>
     <tr>
       <th>Image</th>
       <th>room</th>
       <th>duration / number of guest</th>
       <th>Remove</th>
       <th>Unit price</th>
       <th>Price</th>
       <th>from</th>
       <th>to</th>
     </tr>
   </thead>
   <tbody>
     {% for item in cart %}
       {% with product=item.room %}
         <tr>
           <td>
             <a href="{{ product.get_absolute_url }}">
               <img src="{% if product.image %}{{ product.image.url }}
               {% else %}{% static "img/no_image.png" %}{% endif %}" style="width:20vw;height:30vh">
             </a>
           </td>
           <td>{{ product.number }}</td>
           <td>
             
            {% if product.room_type.name == "meeting" %}
                
            <form action="{% url "cart:cart_add" product.number %}" method="post">
              {{ item.update_room_form.duration }}
              {{ item.update_room_form.override_duration }}
              {{ item.update_room_form.number_of_guest.as_hidden }}
              {{ item.update_room_form.override_number_of_guest }}
              {{ item.update_room_form.start_date }}
              {{ item.update_room_form.end_date }}

              <input type="submit" value="Update">
              {% csrf_token %}
           </form>            

            {% else %}            
            
            <form action="{% url "cart:cart_add" product.number %}" method="post">
              {{ item.update_room_form.duration }}
              {{ item.update_room_form.override_duration }}
              {{ item.update_room_form.number_of_guest }}
              {{ item.update_room_form.override_number_of_guest }}
              {{ item.update_room_form.start_date }}
              {{ item.update_room_form.end_date }}

              <input type="submit" value="Update">
              {% csrf_token %}
           </form>            
          
            
            {% endif %}
            
            </td>
           
           <td>
             <form action="{% url "cart:cart_remove" product.number %}"method="post">
               <input type="submit" value="Remove">
               {% csrf_token %}
             </form>
           </td>
           
           <td class="num">${{ item.price }}</td>
           <td class="num">${{ item.total_price }}</td>
           <td class="num">{{ item.start_date }}</td>
           <td class="num">{{ item.end_date }}</td>
         </tr>
       {% endwith %}
     {% endfor %}
     <tr lass="total">
       <td>Total</td>
       <td colspan="4"></td>
       <td class="num">${{ cart.get_total_price }}</td>
       <td>Total</td>

     </tr>
   </tbody>
 </table>
</div>

 <p class="text-right">
   <a href="{% url "service:booking" %}" class="res_footer"> &larr; back</a>
   {% if request.user.is_authenticated %}
      <div class="cl">
    <button onclick="openPopUp()" class="click">BOOK</button>
   </div>

<div class="pop" id="up">
    <div class="ee" id="xx" onclick="hidePopUP()">&cross;</div>
     <p>payment is made through mpesa</p>
    <form action="{% url "service:account" %}" method="post" name="booking_form">
      {% csrf_token %}
      <div >
             <label for="phone_number">enter phone number for payment</label>
             <input type="tel" name="phone_number" id="phn">

            </div>
        <div>
          <label for="amount">total amount</label>
          <input type="number" name="amount" id="amn" value="{{  cart.get_total_price|floatformat:"2" }}" readonly>
        </div>

        
        <input type="submit" value="pay now" class="log_reg">
        
    </form>
    {% comment %} <a href="{% url "service:account" %}" class="button">DEPOSIT</a> {% endcomment %}

</div>

   {% else %}
   <div class="cl">
    <button class="log_reg"><a href="{% url 'login' %}?next={% url 'cart:cart_detail' %}">Login</a></button> to make a room booking <br> <br>
    <button class="log_reg"><a href="{% url 'service:register' %}?next={% url 'cart:cart_detail' %}">register here</a></button> if you dont hae an account
  </div>

   {% endif %}
   
 </p>
{% endblock %}