cart/urls.py
from django.urls import path
from . import views

app_name = "cart"

urlpatterns = [
    path("", views.cart_detail, name="cart_detail"),
    path("add/<str:room_number>/", views.cart_add, name="cart_add"),
    path("remove/<str:room_number>/", views.cart_remove, name="cart_remove"),
]

hotel/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include
from django.contrib.staticfiles.urls import staticfiles_urlpatterns

urlpatterns = [
    path("", include("service.urls", namespace="service")),
    path("cart/", include("cart.urls", namespace="cart")),
    path("registration", include("service.registration_urls")),
    path("admin/", admin.site.urls),
]


# Serve static files during development
# urlpatterns += staticfiles_urlpatterns()
# urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)


if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

service/urls.py
from django.urls import path, include
from . import views
from django.contrib.auth import views as auth_views
from django.contrib.auth.decorators import login_required


app_name = "service"

urlpatterns = [
    path("", views.Home.as_view(), name="home"),
    path("restaurant/", views.Restaurant_page.as_view(), name="restaurant"),
    path("restaurant/<str:name>/", views.dish_r, name="dish_r"),
    path("wellness/<str:name>/", views.dish_w, name="dish_w"),
    path("about/", views.about, name="about"),
    path("account/", views.account, name="account"),
    path("gallery/", views.gallery, name="gallery"),
    path("wellness/", views.wellness, name="wellness"),
    path("register/", views.register, name="register"),
    path("edit/", views.edit, name="edit"),
    path("events/", views.event, name="event"),
    path("event_info/<str:name>/", views.event_info, name="event_info"),
    path("event_info/delete/<int:id>/", views.delete_reminder, name="delete_r"),
    path("roomt/<int:id>/", views.rooms, name="rooms"),
    path("roomtypes/", views.Roomtype, name="roomtype"),
    path("meeting/", views.meeting, name="meeting"),
    path("booking/", views.booking, name="booking"),
    path("admin_page/", views.admin_page, name="admin"),
    path("email/", views.email_view, name="email_view"),
    path("success/", views.success_page, name="success_page"),
    path('contact/', views.text, name='contact_view'),
    path('success/', views.success_page, name='success_page'),
]

service/forms.py
from django import forms
from django.contrib.auth.models import User
from datetime import datetime, timedelta
from django.utils import timezone
from .models import RoomType


class loginform(forms.Form):
    username = forms.CharField()
    password = forms.CharField(widget=forms.PasswordInput)


class UserRegistrationForm(forms.ModelForm):
    password = forms.CharField(label="Password", widget=forms.PasswordInput)
    password2 = forms.CharField(label="confirm password", widget=forms.PasswordInput)

    class Meta:
        model = User
        fields = ["email", "first_name", "last_name"]

    def clean_password2(self):
        cd = self.cleaned_data
        if cd["password"] != cd["password2"]:
            raise forms.ValidationError("Passwords don't match.")
        return cd["password2"]

    def clean_email(self):
        data = self.cleaned_data["email"]
        if User.objects.filter(email=data).exists():
            raise forms.ValidationError("Email already in use.")
        return data


class UserEditForm(forms.ModelForm):

    class Meta:
        model = User
        fields = ["first_name", "last_name", "email", "username"]

        def clean_username(self):
            name = self.cleaned_data["username"]
            email = self.cleaned_data["email"]
            if User.objects.filter(username=name).exists():
                raise forms.ValidationError("a user with this user name already exist")
            if User.objects.filter(email=email).exists():
                raise forms.ValidationError("Email already in use.")
            return name, email


class ReminderForm(forms.Form):
    reminder_time = forms.DateTimeField(
        widget=forms.DateTimeInput(attrs={"type": "datetime-local"})
    )

    def clean_reminder_time(self):
        reminder_time = self.cleaned_data["reminder_time"]
        if reminder_time <= datetime.now():
            raise forms.ValidationError("Reminder time must be in the future.")
        return reminder_time


# forms.py


class DateRangeForm(forms.Form):
    today = timezone.now().date()
    tomorrow = today + timezone.timedelta(days=1)

    start_date = forms.DateField(
        widget=forms.TextInput(attrs={"type": "date", "value": today}),
        label="Start Date",
        initial=today,
    )
    end_date = forms.DateField(
        widget=forms.TextInput(attrs={"type": "date", "value": tomorrow}),
        label="End Date",
        initial=tomorrow,
    )

    ROOM_TYPE_CHOICES = [("", "All")] + [
        (room_type.id, room_type.name) for room_type in RoomType.objects.all()
    ]

    room_type = forms.ChoiceField(
        choices=ROOM_TYPE_CHOICES, label="Room Type", required=False
    )

    def clean(self):
        cleaned_data = super().clean()
        start_date = cleaned_data.get("start_date")
        end_date = cleaned_data.get("end_date")

        # Ensure start date is not in the past
        if start_date < self.today:
            raise forms.ValidationError("Start date cannot be in the past.")

        # Ensure end date is greater than start date
        if end_date <= start_date:
            raise forms.ValidationError("End date must be greater than start date.")


class RoomAvailabilityForm(forms.Form):
    today = timezone.now().date()

    start_date = forms.DateField(
        label="Start Date",
        widget=forms.DateInput(attrs={"type": "date", "placeholder": today}),
        initial=today,
    )
    duration = forms.IntegerField(
        label="Duration of Stay (in days)",
        initial=1,
        min_value=1,
        widget=forms.NumberInput(attrs={"placeholder": 1}),
    )

    def clean_start_date(self):
        start_date = self.cleaned_data.get("start_date")

        # Ensure start date is not in the past
        if start_date < timezone.now().date():
            raise forms.ValidationError("Start date cannot be in the past.")

        return start_date

    def clean_duration(self):
        duration = self.cleaned_data.get("duration")

        # Ensure duration is a positive integer
        if duration < 1:
            raise forms.ValidationError("Duration must be a positive integer.")

        return duration


class EmailForm(forms.Form):
    email_content = forms.CharField(widget=forms.Textarea, label="Compose Email:")
    specific_user_email = forms.EmailField(
        required=False, label="Send to specific user:"
    )
    send_to_all = forms.BooleanField(required=False, label="Or send to all users")


class ContactForm(forms.Form):
    name = forms.CharField(max_length=100, required=True, label="Your Name")
    email = forms.EmailField(required=True, label="Your Email")
    subject = forms.CharField(max_length=200, required=True, label="Subject")
    message = forms.CharField(widget=forms.Textarea, required=True, label="Message")

service/views.py
# celery -A hotel  worker --pool=solo -l info


from django.shortcuts import render, get_object_or_404, redirect
from .models import (
    Hotel,
    Restaurant,
    Wellness,
    Event,
    Reminder,
    RoomType,
    Room,
    Booking,
    RoomAvailability,
    Review,
    MPesaTransaction,
    PhoneNumber,
)
from django.views.generic import ListView
from django.http import HttpResponse
from django.contrib.auth.models import User
from .forms import (
    loginform,
    UserRegistrationForm,
    UserEditForm,
    ReminderForm,
    DateRangeForm,
    RoomAvailabilityForm,
    ContactForm,
)
from .tasks import send_reminder_email, send_registration_email, send_booking_email
from django.utils import timezone
from django.contrib.auth.forms import AuthenticationForm
from django.db.models import Q, BooleanField, Value, OuterRef, Exists

# GurstEditForm
from django.contrib.auth import authenticate, login
from django.contrib.auth.decorators import login_required
import random
from django.contrib import messages
from datetime import timedelta
from datetime import datetime
from django.core.mail import send_mail
from django.conf import settings
from cart.forms import CartAddRoomForm
from cart.cart import Cart


from django.http import JsonResponse
from django_daraja.mpesa.core import MpesaClient
from django.db import transaction


details = Hotel.objects.all()


class Home(ListView):
    context_object_name = "details"
    template_name = "service/res/index.html"

    def get_queryset(self):
        return Hotel.objects.all()

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)

        queryset1 = Hotel.objects.all()  # queryset for Hotel
        queryset2 = Restaurant.objects.all()
        queryset3 = Wellness.objects.all()
        queryset4 = Event.objects.all()
        queryset5 = RoomType.objects.all()
        form = DateRangeForm()

        context["hotel"] = queryset1
        context["restaurant"] = queryset2[:3]
        context["act"] = queryset3[:3]
        context["event"] = queryset4
        context["rtype"] = queryset5
        context["form"] = form

        return context


class Restaurant_page(ListView):
    context_object_name = "restaurant"
    template_name = "service/res/restaurant.html"

    def get_queryset(self):
        return Restaurant.objects.all()

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)

        queryset1 = Hotel.objects.all()  # queryset for Hotel
        queryset2 = Restaurant.objects.all()

        context["hotel"] = queryset1
        context["restaurant"] = queryset2

        return context


def dish_r(request, name):
    dish = get_object_or_404(Restaurant, name=name)
    hotel = get_object_or_404(Hotel)

    return render(
        request,
        "service/res/dish.html",
        {"dish": dish, "hotel": hotel, "name": "restaurant"},
    )


def dish_w(request, name):
    dish = get_object_or_404(Wellness, name=name)
    hotel = get_object_or_404(Hotel)

    return render(
        request,
        "service/res/dish.html",
        {"hotel": hotel, "dish": dish, "name": "wellness"},
    )


def about(request):
    hotel = Hotel.objects.get(pk=1)
    return render(request, "service/res/about.html", {"hotel": hotel})


def gallery(request):
    hotel = Hotel.objects.all()
    return render(request, "service/res/gallery.html", {"hotel": hotel})


def wellness(request):
    activity = Wellness.objects.all()
    act = activity[:3]
    return render(
        request, "service/res/wellness.html", {"act": act, "activity": activity}
    )


def Roomtype(request):
    rms = RoomType.objects.all()
    return render(request, "service/res/roomtypes.html", {"room": rms})


def rooms(request, id):
    # room = Room.objects.filter(room_type=id)
    room_type = get_object_or_404(RoomType.objects.prefetch_related("amenities"), id=id)
    today = timezone.now().date()
    hotel = get_object_or_404(Hotel)

    form = RoomAvailabilityForm(request.POST or None)
    if request.method == "POST" and form.is_valid():
        start_date = form.cleaned_data["start_date"]
        duration = form.cleaned_data["duration"]
        end_date = start_date + timedelta(days=duration - 1)

        # Filter available rooms based on the selected date range
        available_rooms = Room.objects.filter(
            Q(room_type=id)
            & (
                ~Q(
                    availabilities__start_date__lte=end_date,
                    availabilities__end_date__gte=start_date,
                )
                | ~Q(availabilities__isnull=False)
            )
        ).distinct()

        all_rooms = Room.objects.filter(room_type=id).annotate(
            is_available=Exists(available_rooms.filter(pk=OuterRef("pk")))
        )

        return render(
            request,
            "service/res/rooms.html",
            {
                "hotel": hotel,
                "amn": room_type,
                "name": "roomtype",
                "room": all_rooms,
                "start_date": start_date,
                "duration": duration,
                "form": form,
            },
        )

    start_date = form.initial.get("start_date", today)
    duration = form.initial.get("duration", 1)
    end_date = start_date + timedelta(days=duration - 1)
    room = Room.objects.filter(room_type=id)

    available_rooms = Room.objects.filter(
        Q(room_type=id)
        & (
            ~Q(
                availabilities__start_date__lte=end_date,
                availabilities__end_date__gte=start_date,
            )
            | ~Q(availabilities__isnull=False)
        )
    ).distinct()
    all_rooms = Room.objects.filter(room_type=id).annotate(
        is_available=Exists(available_rooms.filter(pk=OuterRef("pk")))
    )

    return render(
        request,
        "service/res/rooms.html",
        {
            "hotel": hotel,
            "amn": room_type,
            "name": "roomtype",
            "room": all_rooms,
            "today": today,
            "start_date": start_date,
            "duration": duration,
            "form": form,
        },
    )


@transaction.atomic
def account(request):
    hotel = Hotel.objects.all()
    current_user = request.user
    user_reminders = Reminder.objects.filter(user=current_user)
    user_booking = Booking.objects.filter(user=current_user)
    cart = Cart(request)
    bkd_room = {}
    hot = get_object_or_404(Hotel, pk=1)
    hotel_name = hot.name
    if request.method == "POST":

        phone_number = request.POST.get("phone_number")
        am = request.POST.get("amount")
        amn = float(am)
        amount = round(amn)
        account_reference = f"{hotel_name}"
        transaction_desc = f"Payment for booking"

        mpesa_client = MpesaClient()

        try:
            response = mpesa_client.stk_push(
                phone_number,
                amount,
                account_reference,
                transaction_desc,
                callback_url="https://darajambili.herokuapp.com/express-payment",
                # callback_url=settings.MPESA_CALLBACK_URL,
            )

        except Exception as e:
            return f"Mpesa payment initiation failed: {str(e)}"

        phone_number_instance, created = PhoneNumber.objects.get_or_create(
            phone_number=phone_number
        )

        for room in cart:
            current_b = Booking.objects.create(
                user=current_user,
                room=room["room"],
                check_in_date=room["start_date"],
                check_out_date=room["end_date"],
                total_price=room["total_price"],
                payment_status="paid",
            )
            booking_instance = current_b
            MPesaTransaction.objects.create(
                transaction_id=response.checkout_request_id,
                booking=booking_instance,
                amount=amount,
                phone_number=phone_number_instance,
                status="Pending",
            )

            RoomAvailability.objects.create(
                room=room["room"],
                start_date=room["start_date"],
                end_date=room["end_date"],
            )
            room_name = room["room"]
            bkd_room[room_name] = {
                "start_date": room["start_date"],
                "end_date": room["end_date"],
            }
        rooms_info = "; ".join(
            [
                f"{room}: {details['start_date']} - {details['end_date']}"
                for room, details in bkd_room.items()
            ]
        )
        cart.clear()

        subject = "SUCCESFUL ROOM BOOKING"
        message = (
            f"JAMBO! {current_user.username},"
            f"Your booking with {hotel_name} has been successfull. "
            f"Rooms booked:\n{rooms_info}"
            f"Experience luxury at its best. WELCOME!\n\n"
        )
        from_email = settings.EMAIL_HOST_USER
        to_email = [current_user.email]

        send_booking_email.delay(
            subject,
            message,
            from_email,
            to_email,
        )

        # response_des = response.response_description
        # response_data = {"response_des": response_des}
        # return JsonResponse(response_data, safe=False)
    return render(
        request,
        "service/res/account.html",
        {"rmb": user_reminders, "hotel": hotel, "book": user_booking},
    )


def register(request):

    if request.method == "POST":
        user_form = UserRegistrationForm(request.POST)
        if user_form.is_valid():
            rand = random.randint(1000, 10000)
            first_name = user_form.cleaned_data["first_name"]
            username = first_name + str(rand)
            # Create a new user object but avoid saving it yet
            new_user = user_form.save(commit=False)
            # Set the chosen password
            new_user.username = username

service/templates/service/base.html
{% comment %} {% load service_tags %} {% endcomment %}
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>{% block title %}{% endblock  %}</title>
    <link rel="stylesheet" type="text/css" href="{% static 'service/css/style.css' %}">
    <script src="https://kit.fontawesome.com/1ca4691ddb.js" crossorigin="anonymous"></script>
    <link rel="shortcut icon" href="static/service/images/hotel_logo.jpg" type="image/x-icon">
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/swiper@10/swiper-bundle.min.css" />


</head>
<body>
   <div class="header">
    
    <div class="menu_item floater_menu">

        {% if user.is_staff %}
     
        <div><a href="{% url "service:admin" %}"> GO TO ADMIN PAGE</a></div>
        {% endif %}

        <div>  {% with total_items=cart|length %}
        {% if total_items > 0 %}
         <span class="res_room"> rooms reserved:
          <a href="{% url "cart:cart_detail" %}">
            {{ total_items }} room{{ total_items|pluralize }},
            ${{ cart.get_total_price }}
          </a> </span>
        {% else %}
        <span class="res_room"> <a href="{% url "service:booking" %}"> NO room reserved yet</a></span>
        {% endif %}
      {% endwith %}</div>  

    </div>

       <div class="menu">
        
<div class="rich_m">
    <div class="header-icon" onclick="toggleSidebar()">
        <i class="fa-solid fa-bars"></i>
    </div>
    <a href="{% url "service:home" %}"><div class="menu_item"><img src="{% static 'service/images/hotel_logo.jpg' %}" alt="logo" class="header_logo"></div></a>

</div>

<div class="nav_men">
        <div class="menu_item"><a href="{% url 'service:restaurant' %}">RESTOURANT & BAR</a></div>
        <div class="menu_item"><a href="{% url 'service:roomtype' %}">ROOMS & SUITES</a></div>
        <div class="menu_item"><a href="{% url 'service:meeting' %}">MEETING</a></div>
        <div class="menu_item"><a href="{% url "service:about" %}">ABOUT</a></div>
        <div class="menu_item"><a href="{% url 'service:event' %}">EVENTS</a></div>
        <div class="menu_item"><a href="{% url "service:gallery" %}">GALLERY</a></div>
        <div class="menu_item"><a href="{% url 'service:booking' %}">BOOK NOW</a></div>

        


       
        {% if request.user.is_authenticated %}
        <div class="menu_item"><a href="{% url "service:account" %}">my profile <br><i class="fa-solid fa-user"></i></a></div>

        {% else %}
        <div class="menu_item"><a href="{% url "login" %}">LOGIN<br><i class="fa-solid fa-user"></i></a></div>

        {% endif %}
       </div>

       
    </div>
       <div class="sidebar" id="sidebar">
        <button class="exit-button" onclick="toggleSidebar()">X</button>
        <nav>
            <ul>
                <li><a href="{% url "service:home" %}">HOME</a></li>
                <li><a href="{% url "service:restaurant" %}">RESTAURANT & BAR</a></li>
                <li><a href="{% url "service:roomtype" %}">ROOMS</a></li>
                <li><a href="{% url "service:meeting" %}">MEETING</a></li>
                <li><a href="{% url "service:gallery" %}">GALLERY</a></li>
                <li><a href="{% url "service:wellness" %}">WELLNESS</a></li>
                <li><a href="{% url "service:event" %}">EVENTS</a></li>
                <li><a href="{% url "service:booking" %}">BOOK ROOM</a></li>

                {% if request.user.is_authenticated %}
                <li>
                    <form action="{% url "logout"%}" method="POST">
                      <input type="submit" value="LOGOUT">
                      {% csrf_token %}
                    </form>
                 </li>
                {% else %}
                <li><a href="{% url "login" %}">LOG IN</a></li>

                {% endif %}

                <li><a href="{% url "service:about" %}">ABOUT</a></li>
                {% comment %} <li><a href="#c_ftr">CONTACT</a></li> {% endcomment %}
            </ul>
        </nav>
    </div>
   </div>


   {% if messages %}
   <ul class="messages">
     {% for message in messages %}
       <li class="{{ message.tags }}">
         {{ message|safe }}
         <a href="#" class="close">x</a>
       </li>
     {% endfor %}
   </ul>
 {% endif %}

   <div class="content">{% block content %}{% endblock content %}</div>
   
   <div class="footer" id="c_ftr">
      <div class="footer_menu">
         <div class="footer_item imftr"><img src=" {% static 'service/images/hotel_logo.jpg' %}" alt="logo" class="footer_logo"></div>
         <div class="footer_item footer_contact_info">
            <p class="co_in">CONTACT INFORMATION</p>
            <ul>
                {% for hotel in details %}
                <li class="info">{{ hotel.name }}</li>
                <li class="info">{{ hotel.address }}</li>
                <li class="info">{{ hotel.contact_email }}</li>
                <li class="info">{{ hotel.contact_phone }}</li>
                <li class="info"><a href="https://{{ hotel.facebook }}" target="blank">facebook <span><i class="fa-brands fa-facebook"></i></span></a></li>
                <li class="info"><a href="https://{{ hotel.instagram }}" target="blank">instagram <span><i class="fa-brands fa-square-instagram"></i></span></a></li>
                <li class="info"><a href="https://{{ hotel.twitter }}" target="blank">twitter <span><i class="fa-brands fa-twitter"></i></span></a></li>
                {% endfor %}
            </ul>
           
         </div>
         <div class="footer_item footer_hotel_menu">
            <p class="footer_hotel_menu_title"><a href="{% url "service:home" %}">THE HOTEL:</a></p>
            <div class="footer_hotel_menu_item"><a href="{% url "service:restaurant" %}">RESTOURANT & BAR</a></div>
            <div class="footer_hotel_menu_item"><a href="{% url "service:roomtype" %}">ROOMS</a></div>
            <div class="footer_hotel_menu_item"><a href="{% url "service:meeting" %}">MEETING</a></div>
            <div class="footer_hotel_menu_item"><a href="{% url "service:gallery" %}">GALLERY</a></div>
            <div class="footer_hotel_menu_item"><a href="{% url "service:wellness" %}">WELLNESS</a></div>
            <div class="footer_hotel_menu_item"><a href="{% url "service:event" %}">EVENTS</a></div>
            <div class="footer_hotel_menu_item"><a href="{% url "service:booking" %}">BOOK NOW</a></div>

            {% if request.user.is_authenticated %}
                <div>
                    <form action="{% url "logout"%}" method="POST">
                      <input type="submit" value="LOGOUT">
                      {% csrf_token %}
                    </form>
                </div>
                {% else %}
                <div><a href="{% url "login" %}">LOG IN</a></div>

                {% endif %}
                <div class="footer_hotel_menu_item"><a href="{% url "service:about" %}">ABOUT US</a></div>

        
        </div>
          <div class="footer_item icftr">
            <p class="title">FOLLOW US</p>
            <div class="social_icons">
                <div class="icon"><a href=""><i class="fa-brands fa-facebook"></i></a></div>
                <div class="icon"><a href=""><i class="fa-brands fa-twitter"></i></a></div>
                <div class="icon"><a href=""><i class="fa-brands fa-linkedin"></i></a></div>
                <div class="icon"><a href=""><i class="fa-brands fa-square-instagram"></i></a></div>
            </div>
         </div> 
      </div>
    <div class="last_info">
        <div class="last_menu">&copy 2024 {{ details.first }} designed by adams;</div>
        <div class="last_menu">privacy policy</div>
    </div>
   </div> 


   {% comment %} <div class="text" >
    <i class="fa-solid fa-cart-shopping" onclick="openPopUp()"></i>
   </div>

<div class="pop" id="up">
    <div class="ee" id="xx" onclick="hidePopUP()">&cross;</div>
    <p>your cart is empty</p>  
</div> {% endcomment %}



















<script>
    function toggleSidebar() {
        var sidebar = document.getElementById("sidebar");
        if (sidebar.style.left === "0px") {
            sidebar.style.left = "-350px"; // Hide sidebar
        } else {
            sidebar.style.left = "0px"; // Show sidebar
        }
    }
    
    
</script>


<script>
    sap = document.getElementById('up');
    function openPopUp() {
        sap.classList.add('open');
    }

    function hidePopUP() {
        sap.classList.remove('open')
    }
</script>


<script src="https://cdn.jsdelivr.net/npm/swiper@10/swiper-bundle.min.js"></script>
<script>
    const swiper = new Swiper('.swiper', {
        autoplay: {
            delay: 4500,
            disableOnInteraction: false,

        },<!--for aouto,,if you dont want then delete the delay and the disableOnInteraction keys-->

        loop: true,

        // If we need pagination
        pagination: {
            el: '.swiper-pagination',
            clickable: true,
        },

        // Navigation arrows
        navigation: {
            nextEl: '.swiper-button-next',
            prevEl: '.swiper-button-prev',
        },

    }); 
</script>

<script>

document.addEventListener("DOMContentLoaded", function() {
    const gridContainer = document.querySelector('.gallery_images');
    const nextBtn = document.getElementById('next-btn');
    const prevBtn = document.getElementById('prev-btn');
    let currentPage = 1;
    const itemsPerPage = 12; // 4 columns * 2 rows = 8 items

    function showPage(pageNumber) {
        const startIndex = (pageNumber - 1) * itemsPerPage;
        const endIndex = startIndex + itemsPerPage;
        const gridItems = Array.from(gridContainer.children);
        gridItems.forEach((item, index) => {
            if (index >= startIndex && index < endIndex) {
                item.style.display = 'grid'; // Display grid item
            } else {
                item.style.display = 'none'; // Hide grid item
            }
        });
    }

    function nextPage() {
        const totalPages = Math.ceil(gridContainer.children.length / itemsPerPage);
        if (currentPage < totalPages) {
            currentPage++;
            showPage(currentPage);
        }
        else{
            alert("the end")
        }
    
    }

    function prevPage() {
        currentPage--;
        if (currentPage < 1) {
            currentPage = 1;
        }
        showPage(currentPage);
    }

    // Initial display
    showPage(currentPage);

    // Event listeners for pagination controls
    nextBtn.addEventListener('click', nextPage);
    prevBtn.addEventListener('click', prevPage);
});

</script>


<script>

    function showrem(){
        remm = document.getElementById("bigshow")
        remm.style.display="block";
    }
</script>
   





  
</body>
</html>

service/templates/service/base_admin.html
{% comment %} {% load service_tags %} {% endcomment %}
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>{% block title %}{% endblock  %}</title>
    <link rel="stylesheet" type="text/css" href="{% static 'service/css/style.css' %}">
    <script src="https://kit.fontawesome.com/1ca4691ddb.js" crossorigin="anonymous"></script>
    <link rel="shortcut icon" href="static/service/images/hotel_logo.jpg" type="image/x-icon">
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/swiper@10/swiper-bundle.min.css" />


</head>
<body>
   <div class="header">
    
  

       <div class="menu adme">
        

        <div class="menu_item"><a href="{% url 'service:home' %}">HOME</a></div>
        <div class="menu_item"><a href="">EMAILS AND NOTIFICATIONS</a></div>

        <div class="menu_item"><a href="{% url 'admin:index' %}">ADMINISTRATION</a></div>

       </div>      


   </div>


   {% if messages %}
   <ul class="messages">
     {% for message in messages %}
       <li class="{{ message.tags }}">
         {{ message|safe }}
         <a href="#" class="close">x</a>
       </li>
     {% endfor %}
   </ul>
 {% endif %}

   <div class="content">{% block content %}{% endblock content %}</div>
  
   <div class="footer">
    <div class="ft_in">  you are in the admin page</div>
  

   </div>

</body>
</html>