cart/urls.py
from django.urls import path
from . import views

app_name = "cart"

urlpatterns = [
    path("", views.cart_detail, name="cart_detail"),
    path("add/<str:room_number>/", views.cart_add, name="cart_add"),
    path("remove/<str:room_number>/", views.cart_remove, name="cart_remove"),
]

hotel/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include
from django.contrib.staticfiles.urls import staticfiles_urlpatterns

urlpatterns = [
    path("", include("service.urls", namespace="service")),
    path("cart/", include("cart.urls", namespace="cart")),
    path("registration", include("service.registration_urls")),
    path("admin/", admin.site.urls),
]


# Serve static files during development
# urlpatterns += staticfiles_urlpatterns()
# urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)


if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

service/urls.py
from django.urls import path, include
from . import views
from django.contrib.auth import views as auth_views
from django.contrib.auth.decorators import login_required


app_name = "service"

urlpatterns = [
    path("", views.Home.as_view(), name="home"),
    path("restaurant/", views.Restaurant_page.as_view(), name="restaurant"),
    path("restaurant/<str:name>/", views.dish_r, name="dish_r"),
    path("wellness/<str:name>/", views.dish_w, name="dish_w"),
    path("about/", views.about, name="about"),
    path("account/", views.account, name="account"),
    path("gallery/", views.gallery, name="gallery"),
    path("wellness/", views.wellness, name="wellness"),
    path("register/", views.register, name="register"),
    path("edit/", views.edit, name="edit"),
    path("events/", views.event, name="event"),
    path("event_info/<str:name>/", views.event_info, name="event_info"),
    path("event_info/delete/<int:id>/", views.delete_reminder, name="delete_r"),
    path("roomt/<int:id>/", views.rooms, name="rooms"),
    path("roomtypes/", views.Roomtype, name="roomtype"),
    path("meeting/", views.meeting, name="meeting"),
    path("booking/", views.booking, name="booking"),
    path("admin_page/", views.admin_page, name="admin"),
    path("email/", views.email_view, name="email_view"),
    path("success/", views.success_page, name="success_page"),
    path('contact/', views.text, name='contact_view'),
    path('success/', views.success_page, name='success_page'),
]

service/models.py
from django.db import models
from django.contrib.auth.models import User
from django.utils import timezone
from django.urls import reverse


class Hotel(models.Model):
    name = models.CharField(max_length=100)
    description = models.TextField()
    address = models.CharField(max_length=255)
    contact_email = models.EmailField()
    contact_phone = models.CharField(max_length=20)
    facebook = models.CharField(max_length=50)
    instagram = models.CharField(max_length=50)
    twitter = models.CharField(max_length=50)

    def __str__(self):
        return self.name


class Amenity(models.Model):
    name = models.CharField(max_length=100)
    description = models.TextField(
        blank=True, null=True, default=None
    )  # Description of the amenity
    is_available = models.BooleanField(default=True)  # Whether the amenity is active
    icon = models.ImageField(
        upload_to="amenities/icons/", blank=True, null=True
    )  # Icon image for the amenity

    def __str__(self):
        return self.name


class RoomType(models.Model):
    name = models.CharField(max_length=100)
    description = models.TextField()
    capacity = models.IntegerField()
    price = models.DecimalField(max_digits=10, decimal_places=2)
    amenities = models.ManyToManyField(Amenity)
    image = models.ImageField(upload_to="roomtype_images/", default=None)

    def __str__(self):
        return self.name

    def get_absolute_url(self):
        return reverse("service:rooms", args=[self.id])


class Room(models.Model):
    number = models.CharField(max_length=10)
    room_type = models.ForeignKey(
        RoomType, on_delete=models.CASCADE
    )  # each room belongs to exactly ONE type
    hotel = models.ForeignKey(Hotel, on_delete=models.CASCADE)
    beds = models.IntegerField(default=None)
    image = models.ImageField(upload_to="room_images/", default=None)

    def __str__(self):
        return f"{self.room_type.name} - {self.number}"

    def is_available_on(self, date):
        return not self.availabilities.filter(
            start_date__lte=date, end_date__gte=date
        ).exists()

    def is_available_for_dates(self, start_date, end_date):
        return not self.availabilities.filter(
            models.Q(start_date__lte=end_date) & models.Q(end_date__gte=start_date)
        ).exists()


class RoomAvailability(models.Model):
    room = models.ForeignKey(
        Room, related_name="availabilities", on_delete=models.CASCADE
    )
    start_date = models.DateField()
    end_date = models.DateField()

    def __str__(self):
        return f"Room {self.room.number} not available from {self.start_date} to {self.end_date}"

    class Meta:
        constraints = [
            models.CheckConstraint(
                check=models.Q(end_date__gt=models.F("start_date")),
                name="end_date_after_start_date",
            )
        ]

    @property
    def is_currently_unavailable(self):
        today = timezone.now().date()
        return self.start_date <= today <= self.end_date


class Booking(models.Model):
    class status(models.TextChoices):
        pending = "pending"
        paid = "paid"
        not_payed = "payment not made"

    user = models.ForeignKey(User, on_delete=models.CASCADE)
    room = models.ForeignKey(Room, on_delete=models.CASCADE)
    check_in_date = models.DateField()
    check_out_date = models.DateField()
    total_price = models.DecimalField(max_digits=10, decimal_places=2)
    payment_status = models.CharField(max_length=20, choices=status.choices)

    def __str__(self):
        return f"{self.user.username} - {self.room.room_type.name} - {self.check_in_date} to {self.check_out_date}"


class Review(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    room = models.ForeignKey(Room, on_delete=models.CASCADE)
    rating = models.IntegerField()
    review_text = models.TextField()
    date = models.DateField(auto_now_add=True)

    def __str__(self):
        return f"{self.user.username} - {self.room.room_type.name} - {self.date}"


class Event(models.Model):
    name = models.CharField(max_length=255)
    description = models.TextField()
    date = models.DateField()
    start_time = models.TimeField()
    end_time = models.TimeField()
    location = models.CharField(max_length=255)
    image = models.ImageField(upload_to="event_images/")
    organiser = models.CharField(max_length=80)
    entry = models.CharField(max_length=200, default="to be communicated")

    class Meta:
        ordering = ["-date"]

    def __str__(self):
        return self.name

    def get_absolute_url(self):
        return reverse("service:event_info", args=[self.name])


class Restaurant(models.Model):
    name = models.CharField(max_length=150)
    description = models.TextField()
    image = models.ImageField(upload_to="restaurant_images/")
    about = models.TextField(null=True)
    opening = models.TimeField(default=None, null=True)
    closing = models.TimeField(default=None, null=True)

    def get_absolute_url(self):
        return reverse("service:dish_r", args=[self.name])


class Wellness(models.Model):
    name = models.CharField(max_length=100)
    description = models.TextField(blank=True, null=True)
    about = models.TextField()
    is_available = models.BooleanField(default=True)
    opening = models.TimeField()
    closing = models.TimeField()
    image = models.ImageField(upload_to="wellness_images/")

    def get_absolute_url(self):
        return reverse("service:dish_w", args=[self.name])


class Reminder(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE, related_name="user")
    event = models.ForeignKey(Event, on_delete=models.CASCADE, null=True, blank=True)
    booking = models.ForeignKey(
        Booking, on_delete=models.CASCADE, null=True, blank=True
    )
    reminder_time = models.DateTimeField()
    is_seen = models.BooleanField(default=False)
    is_deleted = models.BooleanField(default=False)

    def __str__(self):
        return (
            f"Reminder for {self.event} at {self.reminder_time}"
            if self.event
            else f"Reminder for booking at {self.reminder_time}"
        )


class PhoneNumber(models.Model):
    users = models.ManyToManyField(User, related_name="phone_numbers")
    phone_number = models.CharField(max_length=15)

    def __str__(self):
        return self.phone_number


class MPesaTransaction(models.Model):
    class status(models.TextChoices):
        pending = "pending"
        paid = "paid"
        not_payed = "payment not made"

    transaction_id = models.CharField(max_length=100)
    booking = models.ForeignKey(
        Booking, on_delete=models.CASCADE, related_name="mpesa_transactions"
    )
    amount = models.DecimalField(max_digits=10, decimal_places=2)
    phone_number = models.ForeignKey(
        PhoneNumber, on_delete=models.SET_NULL, null=True, blank=True
    )
    status = models.CharField(max_length=30, choices=status.choices)
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)

    def __str__(self):
        return self.transaction_id

service/forms.py
from django import forms
from django.contrib.auth.models import User
from datetime import datetime, timedelta
from django.utils import timezone
from .models import RoomType


class loginform(forms.Form):
    username = forms.CharField()
    password = forms.CharField(widget=forms.PasswordInput)


class UserRegistrationForm(forms.ModelForm):
    password = forms.CharField(label="Password", widget=forms.PasswordInput)
    password2 = forms.CharField(label="confirm password", widget=forms.PasswordInput)

    class Meta:
        model = User
        fields = ["email", "first_name", "last_name"]

    def clean_password2(self):
        cd = self.cleaned_data
        if cd["password"] != cd["password2"]:
            raise forms.ValidationError("Passwords don't match.")
        return cd["password2"]

    def clean_email(self):
        data = self.cleaned_data["email"]
        if User.objects.filter(email=data).exists():
            raise forms.ValidationError("Email already in use.")
        return data


class UserEditForm(forms.ModelForm):

    class Meta:
        model = User
        fields = ["first_name", "last_name", "email", "username"]

        def clean_username(self):
            name = self.cleaned_data["username"]
            email = self.cleaned_data["email"]
            if User.objects.filter(username=name).exists():
                raise forms.ValidationError("a user with this user name already exist")
            if User.objects.filter(email=email).exists():
                raise forms.ValidationError("Email already in use.")
            return name, email


class ReminderForm(forms.Form):
    reminder_time = forms.DateTimeField(
        widget=forms.DateTimeInput(attrs={"type": "datetime-local"})
    )

    def clean_reminder_time(self):
        reminder_time = self.cleaned_data["reminder_time"]
        if reminder_time <= datetime.now():
            raise forms.ValidationError("Reminder time must be in the future.")
        return reminder_time


# forms.py


class DateRangeForm(forms.Form):
    today = timezone.now().date()
    tomorrow = today + timezone.timedelta(days=1)

    start_date = forms.DateField(
        widget=forms.TextInput(attrs={"type": "date", "value": today}),
        label="Start Date",
        initial=today,
    )
    end_date = forms.DateField(
        widget=forms.TextInput(attrs={"type": "date", "value": tomorrow}),
        label="End Date",
        initial=tomorrow,
    )

    ROOM_TYPE_CHOICES = [("", "All")] + [
        (room_type.id, room_type.name) for room_type in RoomType.objects.all()
    ]

    room_type = forms.ChoiceField(
        choices=ROOM_TYPE_CHOICES, label="Room Type", required=False
    )

    def clean(self):
        cleaned_data = super().clean()
        start_date = cleaned_data.get("start_date")
        end_date = cleaned_data.get("end_date")

        # Ensure start date is not in the past
        if start_date < self.today:
            raise forms.ValidationError("Start date cannot be in the past.")

        # Ensure end date is greater than start date
        if end_date <= start_date:
            raise forms.ValidationError("End date must be greater than start date.")


class RoomAvailabilityForm(forms.Form):
    today = timezone.now().date()

    start_date = forms.DateField(
        label="Start Date",
        widget=forms.DateInput(attrs={"type": "date", "placeholder": today}),
        initial=today,
    )
    duration = forms.IntegerField(
        label="Duration of Stay (in days)",
        initial=1,
        min_value=1,
        widget=forms.NumberInput(attrs={"placeholder": 1}),
    )

    def clean_start_date(self):
        start_date = self.cleaned_data.get("start_date")

        # Ensure start date is not in the past
        if start_date < timezone.now().date():
            raise forms.ValidationError("Start date cannot be in the past.")

        return start_date

    def clean_duration(self):
        duration = self.cleaned_data.get("duration")

        # Ensure duration is a positive integer
        if duration < 1:
            raise forms.ValidationError("Duration must be a positive integer.")

        return duration


class EmailForm(forms.Form):
    email_content = forms.CharField(widget=forms.Textarea, label="Compose Email:")
    specific_user_email = forms.EmailField(
        required=False, label="Send to specific user:"
    )
    send_to_all = forms.BooleanField(required=False, label="Or send to all users")


class ContactForm(forms.Form):
    name = forms.CharField(max_length=100, required=True, label="Your Name")
    email = forms.EmailField(required=True, label="Your Email")
    subject = forms.CharField(max_length=200, required=True, label="Subject")
    message = forms.CharField(widget=forms.Textarea, required=True, label="Message")

service/templates/service/res/about.html
{% extends "service/base.html" %}
{% load static %}
{% load service_tags %}

{% block title %}about_us{% endblock title %}
{% block content %}
<p class="navi">
    <span><a href="{% url "service:home" %}">HOME</a></span> >>
    <span><a href="{% url "service:about" %}">ABOUT</a></span>
</p>


<div class="about_info">
    <p class="about_text">
        ABOUT THE {{ hotel.name|upper }}
    </p>
</div>

<p class="about_text">
    {{ hotel.description|markdown }}
</p>
<div class="about_contact">
 <p class="a_contact_info">
    CONTACT INFORMATION
 </p>
 {% include "service/card.html" %}

</div>

{% endblock content %}

service/templates/service/res/account.html
{% extends "service/base.html" %}
{% load static %}
{% load service_tags %}

{% block title %}
  profile
{% endblock title %}

{% block content %}
  {% for hotel in hotel %}
    <h2 class="acc_int">{{ hotel.name }} WELCOMES <span class="name">{{ request.user.first_name|upper }}</span></h2>
  {% endfor %}

  <div class="acc_manage">
    <div class="ac_logout">
      <form action="{% url "logout"%}" method="POST">
        <input type="submit" value="LOGOUT" class="log_reg">
        {% csrf_token %}
      </form>
    </div>



    <a href="{% url "service:edit" %}" class="log_reg">edit profile</a>

    <a href="{% url "password_change" %}" class="log_reg">change password</a>

    <button class="log_reg" onclick="showrem()"> REMINDERS
    </button>
  </div>

  <div class="rmbook">


    <div class="chumba">
      <p class="acc_rem_title">ROOMS YOU  HAVE BOOKED</p>
      {% if book %}
        <table class="account_booking">
          <thead>
            <tr>
              <th>room image</th>
              <th>room name</th>
              <th> wifi password</th>
              <th>check-in date </th>
              <th>check-out-date</th>
              <th>price</th>
              <th>payment status</th>

            </tr>

          </thead>

          <tbody>
            {% for book in book %}

              <tr>
                <td><img src="{{ book.room.image.url }}" alt="{{ book.room.name }}" style="width: 20vw; height: 30vh;"></td>
                <td>{{ book.room.number }}</td>
                <td>Rayan44@hotel</td>
                <td>{{ book.check_in_date|date:'Y/m/d' }}</td>
                <td>{{ book.check_out_date|date:'Y/m/d' }} </td>
                <td>{{ book.total_price }}</td>
                <td>{{ book.payment_status }}</td>
              </tr>
            {% endfor %}
          </tbody>
        </table>

      {% else %}
        <div class="say">YOU HAVENT BOOK A ROOM YET <br> <br><a href="{% url "service:booking" %}" class="log_reg">book now</a></div>
      {% endif %}
    </div>






    <div class="acc_reminder" id="bigshow">
      <p class="acc_rem_title">REMINDERS</p>
      <div class="acc_rem_holder">
        {% if rmb %}
          {% for alarm  in rmb %}
            <div class="alarm_info">
              <div class="alarm_item">{{ alarm.event }}</div>
 {% comment %} <div class="alarm_item">{{ alarm.booking }}</div> {% endcomment %}
              <div class="alarm_item">{{ alarm.reminder_time }}</div>
              <div class="alarm_item">
                <form action=" {% url "service:delete_r" alarm.id %}" method="post">
                  {% csrf_token %}
                  <input type="submit" value="DELETE">
                </form>
              </div>
            </div>

          {% endfor %}
        {% else %}
          <div class="say">no event reminder set</div>
        {% endif %}

      </div>
    </div>



{% endblock content %}

service/templates/service/res/event_info.html
{% extends "service/base.html" %}
{% load static %}

{% block title %}
    event_info
{% endblock title %}

{% block content %}
    <p class="navigation">
        <span><a href="{% url "service:home" %}">HOME</a></span> >>
        <span><a href="{% url "service:event" %}">EVENTS</a></span> >>
        <span><a href="{{ e_info.get_absolute_url }}">{{ e_info.name|upper }}</a></span>

    </p>

    <p class="e_info_name">
        {{ e_info.name }}
    </p>


    <div class="e_event_info div_brd">
        <div class="e_i_about">
            {{ e_info.description}}
        </div>
        <a href="{{ e_info.image.url }}">
            <div class="e_i_image" target="parent">
                <img src="{{ e_info.image.url }}" alt="{{ e_info.name }}">
            </div>
        </a>

        <div class="e_i_info">

            <p class="e_i_title">DATE: {{ e_info.date }}</p>
            <p class="e_i_title">START-TIME: {{ e_info.start_time }}</p>
            <p class="e_i_title">END_TIME:{{ e_info.end_time }}</p>
            <p class="e_i_title">LOCATION <i class="fa-solid fa-location-dot"></i>:  {{ e_info.location }}</p>
            <p class="e_i_title">ORGANISER: {{ e_info.organiser }}</p>
            <p class="e_i_title">REQUIREMENT: {{ e_info.entry }}</p>

        </div>

        {% if request.user.is_authenticated %}
            <div class="e_i_form">
                <form action="" method="POST">
                    {{ when.as_p }}
                    {% csrf_token %}
                    <input type="submit" value="set reminder">
                </form>
            </div>
        {% else %}
            <div class="e_i_form_not">
                you can <br> <br> <a href="{% url 'login' %}?next={% url 'service:event' %}" class="log_reg">log in</a> <br> <br>  or<br> <br> <a href="{% url "service:register" %}" class="log_reg">register</a><br> <br>  if you dont have an account so as to set reminders to event and enjoy user benefits
            </div>
        {% endif %}

    </div>

{% endblock content %}

service/templates/service/res/events.html
{% extends "service/base.html" %}
{% load static %}

{% block title %}
events
{% endblock title %}

{% block content %}

<p class="navigation">
    <span><a href="{% url "service:home" %}">HOME</a></span> >>
    <span><a href="{% url "service:event" %}">EVENTS</a></span>
</p>

<div class="upcoming">
  <div class="event_title">Upcoming Events</div>
  <div class="event_holder">
    {% for event in upcoming_events %}
    <div class="up_events">
      <div class="evname">
        <div class="event_name">        
            <a href="{{ event.get_absolute_url }}" class="evn">{{ event.name }}</a>
        </div>
        <div class="event_info">
            <a href="{{ event.get_absolute_url }}" class="res_footer">click for more info &rarr;</a>
        </div>
      </div>
      <a href="{{ event.get_absolute_url }}">
        <div class="event_image">
            <img src="{{ event.image.url }}" alt="{{ event.name }}" srcset="">
        </div>
      </a>
    </div>
    {% endfor %}
  </div>
</div>

<div class="event_title pste">Past Events</div>

<div class="past-events">
    <div class="past-events-grid">
      {% for event in past_events %}
      <div class="past-event-item">
        <img src="{{ event.image.url }}" alt="{{ event.name }}">
        <div class="event-date">{{ event.date }}</div>
      </div>
      {% endfor %}
    </div>
  </div>
  
{% endblock content %}

service/templates/service/res/index.html
{% extends "service/base.html" %}
{% load static %}
{% block title %}home {% endblock title %}
{% block content %}
{% for hotel in details %}
<marquee behavior="" direction="right"><span class="hotel_name">WELCOME TO &nbsp;&nbsp;&nbsp; <span class="hot_name">THE {{ hotel.name }}</span></span></marquee>
{% endfor %}

<div class="mth" id="vice">
       <div class="swiper">
         <div class="swiper-wrapper">            
            <div class="swiper-slide ima" id="ser1">
                    
                     <div class="display">
                        <div class="motto">LUXURY AT ITS BEST</div>
                        <div class="logo"><img src="{% static "service/images/hotel_logo.jpg" %}" alt="logo" class="footer_logo"></div>
                     </div>

            </div>
            <div class="swiper-slide ima" id="ser2">

                   
                    <div class="display">
                        <div class="motto">LUXURY AT ITS BEST</div>
                        <div class="logo"><img src="{% static "service/images/hotel_logo.jpg" %}" alt="logo" class="footer_logo"></div>
                     </div>                     

            </div>
            <div class="swiper-slide ima" id="ser3">
               
               
                 <div class="display">
                    <div class="motto">LUXURY AT ITS BEST</div>
                    <div class="logo"><img src="{% static "service/images/hotel_logo.jpg" %}" alt="logo" class="footer_logo"></div>
                 </div>

            </div>
            <div class="swiper-slide ima" id="ser4">

                  
                   <div class="display">
                    <div class="motto">LUXURY AT ITS BEST</div>
                    <div class="logo"><img src="{% static "service/images/hotel_logo.jpg" %}" alt="logo" class="footer_logo"></div>
                 </div>

            </div>
            <div class="swiper-slide ima" id="ser5">

               
                <div class="display">
                    <div class="motto">LUXURY AT ITS BEST</div>
                    <div class="logo"><img src="{% static "service/images/hotel_logo.jpg" %}" alt="logo" class="footer_logo"></div>
                 </div>

            </div>
           
        </div>
        <!-- If we need pagination -->
        <div class="swiper-pagination"></div>
        <!-- If we need navigation buttons -->
        <div class="swiper-button-prev ok"></div>
        <div class="swiper-button-next"></div>
    </div>
</div>




<div class="mth" id="vice">
    
    <!-- Slider main container -->
    <p class="room_suites">ROOMS & SUITES</p>
    <div class="swiper">
        <!-- Additional required wrapper -->
        <div class="swiper-wrapper">
            <!-- Slides -->
        
           {% for rtype in rtype %}
           
            <div class="swiper-slide ima" id="room{{rtype.id}}">
                   
                <div class="display">
                    <a href="{{ rtype.get_absolute_url }}"><div class="image_link">{{ rtype.name }}</div></a>
                    <div class="image_button"><a href="{{ rtype.get_absolute_url }}" class="log_reg">learn more</a></div>
                 </div>
                     <!--content-->

            </div>
            {% endfor %}

        </div>
           
        <div class="swiper-pagination"></div>
        <!-- If we need navigation buttons -->
        <div class="swiper-button-prev"></div>
        <div class="swiper-button-next"></div>
        
    </div>
</div>

<div class="home_booking">
        
    <form method="post" action="{% url "service:booking" %}">

        {% csrf_token %}

        <!-- Start Date Field -->
        <div class="inp">
            <label for="id_start_date" class="lack">Start Date:</label>
            {{ form.start_date }}
           
        </div>
    
        <!-- End Date Field -->
        <div class="inp">
            <label for="id_end_date" class="lack">End Date:</label>
            {{ form.end_date }}
         
        </div>
    
        <!-- Room Type Field -->
 <div class="inp">
            <label for="id_room_type" class="lack">Room Type:</label>
            {{ form.room_type }}
                      
        </div>
        <button type="submit">Check Availability</button>
    
  
       </form>

</div>


<div class="restourant">
        <div class="restaurant_title"><a href="{% url "service:restaurant" %}">RESTOURANT & BAR</a>
            <a href="{% url "service:restaurant" %}" class="res_footer">more &rarr;</a>
        </div>
        <div class="restourant_items">
 
            {% for dish in restaurant %}
            <div class="res_item">
               <a href="{{ dish.get_absolute_url }}"><div class="res_image"><img src="{{ dish.image.url }}" alt="{{ dish.name }}"></div></a> 
                <div class="res_about">
                    <p class="res_about_title">{{ dish.name }}</p>
                    <p class="res_about_info">
                        {{ dish.description }}
                    </p>
                </div>
                
                <div class="res_footer"><a href="{{ dish.get_absolute_url }}">explore &rarr;</a></div>
            </div>

            {% endfor %}

           

            
            
        </div>
    </div>
    
 <div class="meeting">
    <div class="restaurant_title"><a href="{% url "service:meeting" %}">MEETING</a>
        <a href="{% url "service:meeting" %}" class="res_footer">more &rarr;</a>
    </div>    <div class="meeting_image">
        <a href="{% url "service:meeting" %}"><button>more</button></a>
    </div>
 </div>
 <div class="wellness">

    <div class="restaurant_title"><a href="{% url "service:wellness" %}">WELLNESS</a>
    <a href="{% url "service:wellness" %}" class="res_footer">more &rarr;</a>
</div>
<div class="restourant_items">

    

    {% for act in act %}
    <div class="res_item">
       <a href="{{ act.get_absolute_url }}"><div class="res_image"><img src="{{ act.image.url }}" alt="{{ act.name }}"></div></a> 
        <div class="res_about">
          
            <p class="res_about_title">{{ act.name }}</p>
            <p class="res_about_info">
                {{ act.description }}
            </p>
        </div>
        <div class="res_footer"><a href="{{ act.get_absolute_url }}">explore &rarr;</a></div>
    </div>

{% endfor %}


</div>
 </div>
 <div class="gallery">
    <p class="gallery_title"><a href="{% url "service:event" %}">EVENTS</a> & <a href="{% url "service:gallery" %}">GALLERY</a> </p>
    <div class="gallery_items">
        

        <div class="res_item">
           <a href="{% url "service:event" %}"><div class="res_image"><img src="{{ event.first.image.url }}" alt="art"></div></a> 
            <div class="res_about">
                <p class="res_about_title"><a href="{% url "service:event" %}">EVENTS</a></p>
                <p class="res_about_info">
                    A series of diverse and entertaining cultural events with both local & international expert guests.</div>
            <div class="res_footer"><a href="{% url "service:event" %}">explore &rarr;</a></div>
        </div>

        <div class="res_item">
           <a href="{% url "service:gallery" %}"><div class="res_image"><img src="{% static 'service/images/gallery.jpg' %}" alt="gallery"></div></a> 
            <div class="res_about">
                <p class="res_about_title"><a href="{% url "service:gallery" %}">GALLERY</p></a>
                <p class="res_about_info">
                    Read more about The st.rayan, its fascinating history, vibrant surroundings, place in the Tel Aviv culinary scene and it’s passionate people.            </div>
            <div class="res_footer"><a href="{% url "service:gallery" %}">explore &rarr;</div></a>
        </div>

    </div>
 </div>
{% endblock content %}

service/templates/service/res/meeting.html
{% extends "service/base.html" %}
{% load static %}

{% block title %}
    meeting
{% endblock title %}

{% block content %}

    <p class="navigation">
        <span><a href="{% url "service:home" %}">HOME</a></span> >>
        <span><a href="{% url "service:meeting" %}">MEETING</a></span>
    </p>




{% endblock content %}

service/templates/service/res/success.html
{% extends "service/base_admin.html" %}
{% block title %}Success{% endblock title %}

{% block content %}
<h1>Email Sent Successfully!</h1>
<p>Your email has been sent successfully.</p>
<a href="{% url 'service:admin' %}">Back to Admin Page</a>
{% endblock content %}